# serverless.yml

service: apollo-lambda

plugins:
  - serverless-plugin-typescript
provider:
  name: aws
  runtime: nodejs14.x
  region: ap-southeast-2
functions:
  graphql:
    # this is formatted as <FILENAME>.<HANDLER>
    handler: graphql.graphqlHandler
    events:
    - http:
        path: /
        method: post
        cors: true
    - http:
        path: /
        method: get
        cors: true
