# serverless.yml

service: apollo-lambda

custom:
  serverless-offline:
    httpPort: 4000
    websocketPort: 4001
plugins:
  - serverless-plugin-typescript
  - serverless-offline
provider:
  name: aws
  runtime: nodejs14.x
  region: ap-southeast-2
functions:
  graphql:
    # this is formatted as <FILENAME>.<HANDLER>
    handler: src/graphql.graphqlHandler
    events:
    - http:
        path: /
        method: post
        cors: true
    - http:
        path: /
        method: get
        cors: true
